### PR TITLE
fix: Reflect the changes in the ebs_csi driver

### PR DESCRIPTION
**Pull request by prysmakou-sa**
## Description

modules/iam-role-for-service-accounts-eks -
EBS-CSI driver policy - fix condition string for DeleteVolume action to reflect the changes in the upstream

## Motivation and Context
Issue - https://github.com/terraform-aws-modules/terraform-aws-iam/issues/325
The change in the upstream - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1450

## Breaking Changes
There are no breaking changes

## How Has This Been Tested?
- [x] I have executed `pre-commit run -a` on my pull request
- tested on the EKS 1.23, Chart: aws-ebs-csi-driver-2.11.1, the driver version: 1.11.3

### CODE REVIEW

**Comment by bryantbiggs** [comment]
so the change looks great - makes sense. However, for users who are using versions < 2.14.1, this will break their permissions - *I think. 

So we'll need to somehow factor that into the change - I don't know if the CSI drivers still support the old route with the cluster owned, open to ideas though

**Comment by prysmakou-sa** [comment]
@bryantbiggs just to be on the safe side we could let loose the permissions for a while: to save the current/former statement and add the new one. What do you think?

**Comment by prysmakou-sa** [comment]
I have updated the PR so now we do not replace the condition but add the new statement.

**Review by bryantbiggs — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 5.11.1 :tada:

**Pull request merged**
