### PR TITLE
adding override_json variable to data policy document and adding trusted_role_action to iam-assumable-roles

### PR DESCRIPTION
**Pull request by tcharewicz**
## Description
Adding variable assume_role_policy, and use it at data policy document level as a override_json.

## Motivation and Context
You can create any proper assume policy document and pass it to the IAM module.

## Breaking Changes
None

## How Has This Been Tested?
Right now this changes arn't tested with examples presented at repository. If maintainer accept this way of configuration I will make this tests.

### CODE REVIEW

**Comment by fn-jbarker** [comment]
This would have been a nice feature for me recently.  The either or scenario with mfa didn't allow me to entertain the scenario where we have humans interacting with the role in addition to a service account interacting with the role.  Both needed to assume the role, but the service account isn't required to be mfa authenticated.

**Comment by fn-jbarker** [comment]
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::000000000000:root"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "Bool": {
          "aws:MultiFactorAuthPresent": "true"
        }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::000000000000:role/madeuprole"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}`

**Comment by fn-jbarker** [comment]
Thoughts on this @antonbabenko?

**Review by antonbabenko — CHANGES_REQUESTED** [review]
Looks very good (skip CI failures, I will fix those after this PR is done). Could you update code in the examples for the affected modules to show `assume_role_policy` in action?

**Pull request closed without merging**
