### PR TITLE
feat: Enables exclusive IAM policy management of IAM role with managed_policy_arns option

### PR DESCRIPTION
**Pull request by sksmsWKd**
## Description

This PR supports exclusive management of policy attachments on IAM role.

For prevent resource cycling error, `managed_policy_arns`  can't be used with these resources :  :`aws_iam_role_policy_attachment` or `aws_iam_role_policy`.

## Motivation and Context

When using `aws_iam_role` and this module with the `moved` command for refactoring (i mean refactor my resource with this module),
although my `aws_iam_role` already contains `managed_policy_arns`, 
the `managed_policy_arns` could not be set, so the dependency between IAM role and IAM policy could not be left as code, so `aws_iam_role_policy_attachment` had to be added as resource.

To prevent unexpected IAM policy changes, i thought adding `managed_policy_arns` option to IAM role can be clear choice for exclusive management of IAM role's policy.

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by sksmsWKd** [comment]
Hello [@bryantbiggs](https://github.com/bryantbiggs) , Cloud you review my PR, please.

**Comment by sksmsWKd** [comment]
Hello [@bryantbiggs](https://github.com/bryantbiggs), [@antonbabenko](https://github.com/antonbabenko), Cloud you review my PR, please.

**Comment by GedriteA** [comment]
+1 we could use this

**Comment by sksmsWKd** [comment]
Hello [@bryantbiggs](https://github.com/bryantbiggs), [@antonbabenko](https://github.com/antonbabenko), Cloud you review my PR, please.

**Comment by bryantbiggs** [comment]
I don't understand the problem nor the changes proposed

**Comment by joan-s-molas** [comment]
`aws_iam_role.managed_policy_arns` has been deprecated, so that would not be the best approach.

I believe what @sksmsWKd is trying to achieve is to prevent manually made changes to the policy attachments for that role (via console or cli) to persist between terraform runs. I.e, someone attaches a policy to the terraformed role via the console - that gets reverted when terraform is applied again.

The way to go around this should probably be allowing the use of `aws_iam_role_policy_attachments_exclusive` or similar.

**Comment by sksmsWKd** [comment]
.

**Comment by bryantbiggs** [comment]
> I believe what @sksmsWKd is trying to achieve is to prevent manually made changes to the policy attachments for that role (via console or cli) to persist between terraform runs. I.e, someone attaches a policy to the terraformed role via the console - that gets reverted when terraform is applied again.
> 
> `aws_iam_role.managed_policy_arns` has been deprecated, so that would not be the best approach.
> 
> The way to go around this should probably be implementing the optional use of `aws_iam_role_policy_attachments_exclusive` or similar.

that may or may not be the case, I don't know. we should start with an issue first that describes the challenge so we can understand better before we jump into code changes. closing this for now till we see more around the challenge

**Comment by sksmsWKd** [comment]
@bryantbiggs 
thanks for your comment & feedback. i'll start with an issue first when the issue becomes clear.

**Pull request closed without merging**
