### PR TITLE
feat: Add support for inline policy creation

### LINKED ISSUE #261: how to create inline policy w with assumable role
I want to create inline policy with  assumable role.

Currently,i see it only supports custom policy arn not  inline policy JSON.

Could you please how to create inline policy with assumable role.

My IAM role contains customer managed policy ,aws managed policyband inlinepolicy.

Current module setup only supporting aws and customer mananged policy.

Please suggest.

### LINKED ISSUE #419: feat: Support `inline-policy` in iam-assumable-role
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

I don't know which provider version initially introduced the functionality, but specifying an `inline_policy` has been core to IAM for years.

## Is your request related to a problem? Please describe.

Yes, it is currently not possible for me to use this module by itself and requires an accompanying resource to use. In my use case, I use terragrunt and would like to specify *just* the `iam-assumable-role` module as it has everything I need, except for the ability to specify a custom, inline policy.

## Describe the solution you'd like.

I'd like to see [inline_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role#inline_policy) supported when calling `aws_iam_role` [here](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-assumable-role/main.tf#L142), while allowing the user to specify a custom inline policy the same way they can feed in a custom [role trust policy](https://github.com/terraform-aws-modules/terraform-aws-iam/blob/master/modules/iam-assumable-role/main.tf#L9).

This would allow me to easily call this module in terragrunt without having to specify my own custom module to call this module with one additional managed policy like so:

```hcl
terraform {
  source = "git@github.com:terraform-aws-modules/terraform-aws-iam//modules/iam-assumable-role?ref=856b5438e91dd87c1e9d225afd123769aaadb635" # 5.30.0
}

inputs = {
  create_role = true
  role_name = "my_role"
  inline_policy = <my_json_encoded_policy>
}
```

This was originally requested in #261, but was closed due to inactivity.

## Describe alternatives you've considered.

The alternative is to create a secondary module that calls `iam-assumable-role` and a singular policy, then passes the created policy back to the module. I don't have a need to create a managed policy - just a single inline policy on the role.

## Additional context

N/A

### LINKED ISSUE #463: Inline Policy
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

Is possible to create an inline-policy within the iam rol?

```
module "iam_assumable_role_admin" {
  source = "../../modules/iam-assumable-role"
  create_role = true
  trusted_role_services = [
    "lambda.amazonaws.com"
  ]
  role_name = "NaranjaDataLakeStack-odlLambdaCreateEMRRole-15O2CRK2MW8HK"

  # --> INLINE POLICY HERE

  }
  ```

### PR DESCRIPTION
**Pull request by fatmcgav**
## Description
This commit adds support for creating an inline policy for an IAM role to the `iam-assumable-role-with-oidc` and `iam-assumable-role` modules.

Also updated examples for these modules.

## Motivation and Context
Allows creation of an IAM role with an inline policy. 
- Resolves #463 
- Resolves #419 
- Resolves #261 

## Breaking Changes
None

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by fatmcgav** [comment]
@bryantbiggs Any chance of a review on this one? 😎

**Comment by fatmcgav** [comment]
@bryantbiggs / @antonbabenko Any chance of a review on this one? 👍

**Comment by bryantbiggs** [comment]
why are we creating examples that look like users should be using https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks ?

**Comment by fatmcgav** [comment]
> why are we creating examples that look like users should be using https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-role-for-service-accounts-eks ?

So for my use case, I needed to be able to add an inline policy to a role that's assumed by a 3rd party service, _not_ by EKS...

**Comment by bryantbiggs** [comment]
that doesn't really explain why the examples added are IRSA related?

**Comment by fatmcgav** [comment]
> that doesn't really explain why the examples added are IRSA related?

Ah, ok... that was probably a poor copy'n'paste on my part... Will re-work to show a CircleCI related example...

**Comment by bryantbiggs** [comment]
thank you - it doesn't have to fully function, you can make up OIDC provider details just to demonstrate the point (i.e. - we don't test whether the authentication flow between the role and the OIDC provider works correctly)

and the implementation is currently quite lacking - here is a reference that is closer to what we could support https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3087

**Comment by fatmcgav** [comment]
> and the implementation is currently quite lacking - here is a reference that is closer to what we could support [terraform-aws-modules/terraform-aws-eks#3087](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3087)

Nice... I'll replicate here 👍

**Comment by fatmcgav** [comment]
RIght, I've pushed a couple of updates based on the changes from https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3087 and also tweaked the oidc examples to reference CircleCI.

@bryantbiggs Let me know what you think 👍

**Review by bryantbiggs — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 5.40.0 :tada:

**Pull request merged**
