### PR TITLE
fix: Add `ssm:DescribeParameters` permission to `external-secrets` IAM role for service account (IRSA)

### PR DESCRIPTION
**Pull request by jaydeland**
ssm:DescribeParameters is required to sync secrets from ParameterStore

## Description
Error from the external-secrets log:
aws-role is not authorized to perform: ssm:DescribeParameters on resource: * because no identity-based policy allows the ssm:DescribeParameters action\n\tstatus code: 400, request id: ff","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/e │

## Motivation and Context
When using AWS System Manager Parameters with external-secrets(ESO) the secrets can not be synced unless the AWS Role that is mapped to the EKS Service Account has the ssm:DescribeParameters action.

## How Has This Been Tested?
1. Using the module: `"terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"`
2. provider: aws
3. ESO SecretStore with 
```
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: <sa_name>
```
4. Other values passed to the module
``` 
attach_external_secrets_policy = true
allow_self_assume_role = true
```
- [x] I have executed `pre-commit run -a` on my pull request

```
pre-commit run -a
[INFO] Initializing environment for https://github.com/antonbabenko/pre-commit-terraform.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Terraform fmt............................................................Passed
Terraform validate.......................................................Passed
Terraform docs...........................................................Passed
Terraform validate with tflint...........................................Passed
check for merge conflicts................................................Passed
fix end of files.........................................................Passed
```

### CODE REVIEW

**Comment by jaydeland** [comment]
@antonbabenko - Am I missing anything else to get this PR approved?

**Comment by bryantbiggs** [comment]
are you sure this will work or does it need to be a wildcard? https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1504

**Review by bryantbiggs — APPROVED** [review]
seems safe enough to try as is since the ARNs are in the users control - thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 5.14.2 :tada:

**Pull request merged**
