### PR TITLE
feat: Extend self-management policy to read account summary (iam-group-with-policies)

### PR DESCRIPTION
**Pull request by vutny**
## Description
This PR extends default self-management policy for IAM group with permissions to read account summary.

## Motivation and Context
This change is necessary to have a clean view of IAM Dashboard in AWS Console for authenticated IAM user with self-management policy.
It allows to:
* see AWS account general security recommendations, which is always good to have
* see current AWS account ID and Alias in AWS Console, it is useful when using "Switch Role" wizard with account alias

## Breaking Changes
None.

## How Has This Been Tested?
Applied default policy and checked through AWS Console.

### CODE REVIEW

**Review by antonbabenko — APPROVED** [review]

**Comment by antonbabenko** [comment]
Could you please upgrade pre-commit-terraform version to the latest (more than [1.87.0](https://github.com/antonbabenko/pre-commit-terraform/blob/master/CHANGELOG.md#1870-2024-02-17))?

**Comment by bryantbiggs** [comment]
pre-commit has been updated to latest in #459 - :shipit:

**Comment by antonbabenko** [comment]
This PR is included in version 5.37.0 :tada:

**Comment by vutny** [comment]
Thanks!

**Comment by vutny** [comment]
@antonbabenko , @bryantbiggs The version `5.37.0` is still missing in the registry: https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest
Can you upload please? :pray:

**Comment by antonbabenko** [comment]
Weird. I have raised a ticket with the Terraform Registry to figure out what has been happening with it, but they still have not replied during the last 3 days. This has been an issue in many other repositories. Manually clicking "resync module" doesn't work anymore.

/cc @bryantbiggs FYI

**Comment by vutny** [comment]
Now it is there, thank you.

**Comment by antonbabenko** [comment]
They said there was an incident - https://status.hashicorp.com/incidents/jsp31wyh8mhl

**Pull request merged**
