### PR TITLE
docs: Updated example in README

### PR DESCRIPTION
**Pull request by ArieLevs**
# Description

While trying to implement the `iam-assumable-role-with-oidc` module, it didn't worked out of the box,
then i noticed the readme used a wrong module the `iam-assumable-role`.

### CODE REVIEW

**Comment by ArieLevs** [comment]
@antonbabenko @max-rocket-internet 
Hi there are no owners file, so i've tagged you guys, can you please take a look

**Comment by ArieLevs** [comment]
@max-rocket-internet Can it be merged?

**Comment by antonbabenko** [comment]
Hi Arie,

I will merge on Monday.

**Comment by ArieLevs** [comment]
@antonbabenko 
ping

**Pull request merged**
